/**
 * Tensor-backed vector representations with explicit semantic space identity
 * (Python ``tensorcode/ops/vec/latent.py``). FOUNDATION-OWNED: vector builders
 * import these records but do not edit this file.
 */
import { Tensor } from '../../nn/tensor.js';
import { torchDTypeName } from '../../nn/dtype.js';
import { ValueError } from '../../errors.js';
import { rejectUnknownFields } from '../../_internal/operationConfig.js';
import { isPlainObject } from '../../_internal/json.js';

export interface SpaceOptions {
  version?: string;
  organization?: string;
  /** Python dtype spelling, e.g. ``'torch.float32'``. */
  dtype?: string | null;
  device?: string | null;
}

export interface SpaceConfiguration {
  name: string;
  dimensions: number;
  version: string;
  organization: string;
  dtype: string | null;
  device: string | null;
}

/**
 * Identity and shape contract for a vector representation. A matching
 * dimension is insufficient for compatibility: name, version, organization
 * and optional dtype/device requirements must also match. ``organization``
 * describes mechanics (``feature``, ``sequence``, ``spatial``), not semantics.
 */
export class Space {
  static readonly qualifiedName: string = 'tensorcode.ops.vec.latent.Space';
  static readonly recordFields = ['name', 'dimensions', 'version', 'organization', 'dtype', 'device'] as const;
  readonly name: string;
  readonly dimensions: number;
  readonly version: string;
  readonly organization: string;
  readonly dtype: string | null;
  readonly device: string | null;

  constructor(name: string, dimensions: number, options: SpaceOptions = {}) {
    const version = options.version ?? '1';
    const organization = options.organization ?? 'feature';
    const dtype = options.dtype ?? null;
    const device = options.device ?? null;
    if (typeof name !== 'string' || !name) throw new ValueError('Space name must be a nonempty string');
    if (typeof dimensions !== 'number' || !Number.isInteger(dimensions) || dimensions <= 0) {
      throw new ValueError('Space dimensions must be a positive integer');
    }
    if (typeof version !== 'string' || !version) throw new ValueError('Space version must be a nonempty string');
    if (typeof organization !== 'string' || !organization) throw new ValueError('Space organization must be a nonempty string');
    if (dtype !== null && (typeof dtype !== 'string' || !dtype)) throw new ValueError('Space dtype must be a nonempty string or None');
    if (device !== null && (typeof device !== 'string' || !device)) throw new ValueError('Space device must be a nonempty string or None');
    this.name = name;
    this.dimensions = dimensions;
    this.version = version;
    this.organization = organization;
    this.dtype = dtype;
    this.device = device;
    Object.freeze(this);
  }

  /** Construct from a configuration mapping (Python ``Space(**config)``). */
  static fromConfig(config: unknown): Space {
    if (config instanceof Space) return config;
    if (!isPlainObject(config)) throw new TypeError('space must be a Space or its configuration object');
    rejectUnknownFields(config, Space.recordFields, 'Unknown Space fields');
    const { name, dimensions, version, organization, dtype, device } = config as Partial<SpaceConfiguration>;
    if (name === undefined || dimensions === undefined) throw new TypeError('Space configuration requires name and dimensions');
    return new Space(name, dimensions, {
      ...(version !== undefined ? { version } : {}), ...(organization !== undefined ? { organization } : {}),
      dtype: dtype ?? null, device: device ?? null,
    });
  }

  static fromRecord(fields: Record<string, unknown>): Space {
    return Space.fromConfig(fields);
  }

  toRecord(): Record<string, unknown> {
    return this.configuration() as unknown as Record<string, unknown>;
  }

  configuration(): SpaceConfiguration {
    return {
      name: this.name, dimensions: this.dimensions, version: this.version,
      organization: this.organization, dtype: this.dtype, device: this.device,
    };
  }

  equals(other: unknown): boolean {
    return other instanceof Space && other.name === this.name && other.dimensions === this.dimensions
      && other.version === this.version && other.organization === this.organization
      && other.dtype === this.dtype && other.device === this.device;
  }

  toString(): string {
    return `Space(name=${JSON.stringify(this.name)}, dimensions=${this.dimensions}, version=${JSON.stringify(this.version)}, `
      + `organization=${JSON.stringify(this.organization)}, dtype=${JSON.stringify(this.dtype)}, device=${JSON.stringify(this.device)})`;
  }
}

export interface LatentOptions {
  mask?: Tensor | null;
  coordinates?: Tensor | null;
  sources?: Iterable<string>;
  metadata?: Record<string, unknown> | null;
}

/** A tensor plus the information required to consume it safely. */
export class Latent {
  static readonly qualifiedName: string = 'tensorcode.ops.vec.latent.Latent';
  static readonly recordFields = ['tensor', 'space', 'mask', 'coordinates', 'sources', 'metadata'] as const;
  readonly tensor: Tensor;
  readonly space: Space;
  readonly mask: Tensor | null;
  readonly coordinates: Tensor | null;
  readonly sources: readonly string[];
  readonly metadata: Readonly<Record<string, unknown>>;

  constructor(tensor: Tensor, space: Space, options: LatentOptions = {}) {
    if (!(tensor instanceof Tensor)) throw new TypeError('Latent tensor must be a Tensor');
    if (!(space instanceof Space)) throw new TypeError('Latent space must be a Space');
    if (tensor.ndim < 1 || tensor.shape[tensor.ndim - 1] !== space.dimensions) {
      throw new ValueError(`Latent feature dimension must be ${space.dimensions}, received shape [${tensor.shape.join(', ')}]`);
    }
    if (space.dtype !== null && torchDTypeName(tensor.dtype) !== space.dtype) {
      throw new ValueError(`Latent dtype must be ${space.dtype}, received ${torchDTypeName(tensor.dtype)}`);
    }
    if (space.device !== null && space.device !== 'cpu') {
      throw new ValueError(`Latent device must be ${space.device}, received cpu`);
    }
    const prefix = tensor.shape.slice(0, -1);
    const mask = options.mask ?? null;
    if (mask !== null && (!(mask instanceof Tensor) || !sameShape(mask.shape, prefix))) {
      throw new ValueError(`Latent mask shape must be [${prefix.join(', ')}]`);
    }
    const coordinates = options.coordinates ?? null;
    if (coordinates !== null && (!(coordinates instanceof Tensor) || coordinates.ndim !== tensor.ndim
      || !sameShape(coordinates.shape.slice(0, -1), prefix) || coordinates.shape[coordinates.ndim - 1]! < 1)) {
      throw new ValueError("Latent coordinates must have the tensor's leading shape and a final coordinate dimension");
    }
    const sources = Object.freeze([...(options.sources ?? [])]);
    if (!sources.every((source) => typeof source === 'string')) throw new TypeError('Latent sources must be strings');
    const metadata = options.metadata ?? {};
    if (!isPlainObject(metadata)) throw new TypeError('Latent metadata must be a mapping');
    this.tensor = tensor;
    this.space = space;
    this.mask = mask;
    this.coordinates = coordinates;
    this.sources = sources;
    this.metadata = Object.freeze({ ...metadata });
    Object.freeze(this);
  }

  static fromRecord(fields: Record<string, unknown>): Latent {
    return new Latent(fields.tensor as Tensor, fields.space as Space, {
      mask: (fields.mask as Tensor | null) ?? null,
      coordinates: (fields.coordinates as Tensor | null) ?? null,
      sources: (fields.sources as readonly string[] | undefined) ?? [],
      metadata: (fields.metadata as Record<string, unknown> | null) ?? {},
    });
  }

  toRecord(): Record<string, unknown> {
    return {
      tensor: this.tensor, space: this.space, mask: this.mask, coordinates: this.coordinates,
      sources: this.sources, metadata: this.metadata,
    };
  }

  /** Carry provenance onto a new tensor without detaching autograd (mask/coordinates are not carried implicitly). */
  withTensor(tensor: Tensor, options: { space?: Space; mask?: Tensor | null; coordinates?: Tensor | null } = {}): Latent {
    return new Latent(tensor, options.space ?? this.space, {
      mask: options.mask ?? null, coordinates: options.coordinates ?? null,
      sources: this.sources, metadata: this.metadata as Record<string, unknown>,
    });
  }
}

function sameShape(a: readonly number[], b: readonly number[]): boolean {
  return a.length === b.length && a.every((size, index) => size === b[index]);
}

export function requireCompatible(expected: Space, actual: Space, options: { role?: string } = {}): void {
  if (!expected.equals(actual)) {
    throw new ValueError(`${options.role ?? 'input'} has incompatible vector space: expected ${expected}, received ${actual}`);
  }
}

/** Explicit trusted types for durable vector experience serialization (Python ``vec.latent_codecs()``). */
export function latentCodecs(): { 'tensorcode.Latent': typeof Latent; 'tensorcode.Space': typeof Space } {
  return { 'tensorcode.Latent': Latent, 'tensorcode.Space': Space };
}
