/* eslint-disable */
// GENERATED by scripts/codegen/diffusers_defaults.py from diffusers 0.40.0. Do not edit by hand.
import type { JsonObject } from '../json.js';

export const DIFFUSERS_VERSION = "0.40.0";

export const DIFFUSERS_CONFIG_DEFAULTS: Record<string, JsonObject> = {
  "UNet2DConditionModel": {
    "sample_size": null,
    "in_channels": 4,
    "out_channels": 4,
    "center_input_sample": false,
    "flip_sin_to_cos": true,
    "freq_shift": 0,
    "down_block_types": [
      "CrossAttnDownBlock2D",
      "CrossAttnDownBlock2D",
      "CrossAttnDownBlock2D",
      "DownBlock2D"
    ],
    "mid_block_type": "UNetMidBlock2DCrossAttn",
    "up_block_types": [
      "UpBlock2D",
      "CrossAttnUpBlock2D",
      "CrossAttnUpBlock2D",
      "CrossAttnUpBlock2D"
    ],
    "only_cross_attention": false,
    "block_out_channels": [
      320,
      640,
      1280,
      1280
    ],
    "layers_per_block": 2,
    "downsample_padding": 1,
    "mid_block_scale_factor": 1,
    "dropout": 0.0,
    "act_fn": "silu",
    "norm_num_groups": 32,
    "norm_eps": 1e-05,
    "cross_attention_dim": 1280,
    "transformer_layers_per_block": 1,
    "reverse_transformer_layers_per_block": null,
    "encoder_hid_dim": null,
    "encoder_hid_dim_type": null,
    "attention_head_dim": 8,
    "num_attention_heads": null,
    "dual_cross_attention": false,
    "use_linear_projection": false,
    "class_embed_type": null,
    "addition_embed_type": null,
    "addition_time_embed_dim": null,
    "num_class_embeds": null,
    "upcast_attention": false,
    "resnet_time_scale_shift": "default",
    "resnet_skip_time_act": false,
    "resnet_out_scale_factor": 1.0,
    "time_embedding_type": "positional",
    "time_embedding_dim": null,
    "time_embedding_act_fn": null,
    "timestep_post_act": null,
    "time_cond_proj_dim": null,
    "conv_in_kernel": 3,
    "conv_out_kernel": 3,
    "projection_class_embeddings_input_dim": null,
    "attention_type": "default",
    "class_embeddings_concat": false,
    "mid_block_only_cross_attention": null,
    "cross_attention_norm": null,
    "addition_embed_type_num_heads": 64
  },
  "AutoencoderKL": {
    "in_channels": 3,
    "out_channels": 3,
    "down_block_types": [
      "DownEncoderBlock2D"
    ],
    "up_block_types": [
      "UpDecoderBlock2D"
    ],
    "block_out_channels": [
      64
    ],
    "layers_per_block": 1,
    "act_fn": "silu",
    "latent_channels": 4,
    "norm_num_groups": 32,
    "sample_size": 32,
    "scaling_factor": 0.18215,
    "shift_factor": null,
    "latents_mean": null,
    "latents_std": null,
    "force_upcast": true,
    "use_quant_conv": true,
    "use_post_quant_conv": true,
    "mid_block_add_attention": true
  },
  "DDIMScheduler": {
    "num_train_timesteps": 1000,
    "beta_start": 0.0001,
    "beta_end": 0.02,
    "beta_schedule": "linear",
    "trained_betas": null,
    "clip_sample": true,
    "set_alpha_to_one": true,
    "steps_offset": 0,
    "prediction_type": "epsilon",
    "thresholding": false,
    "dynamic_thresholding_ratio": 0.995,
    "clip_sample_range": 1.0,
    "sample_max_value": 1.0,
    "timestep_spacing": "leading",
    "rescale_betas_zero_snr": false
  }
};
