/**
 * Immutable message records (Python ``tensorcode/ops/text/messages.py``).
 * FOUNDATION-OWNED: text builders import these records but do not edit this file.
 * Record fields keep the Python snake_case spelling for persistence.
 */
import { ValueError } from '../../errors.js';

export type MessageRole = 'system' | 'user' | 'assistant' | 'tool';
export type ImageDetail = 'low' | 'high' | 'auto';

/** An immutable text segment with an optional caller-owned source ID. */
export class TextPart {
  static readonly qualifiedName: string = 'tensorcode.ops.text.messages.TextPart';
  static readonly recordFields = ['text', 'source_ref'] as const;
  readonly text: string;
  readonly sourceRef: string | null;

  constructor(text: string, options: { sourceRef?: string | null } = {}) {
    if (typeof text !== 'string') throw new TypeError('TextPart.text must be a string');
    const sourceRef = options.sourceRef ?? null;
    if (sourceRef !== null && typeof sourceRef !== 'string') throw new TypeError('TextPart.source_ref must be a string or None');
    this.text = text;
    this.sourceRef = sourceRef;
    Object.freeze(this);
  }

  static fromRecord(fields: Record<string, unknown>): TextPart {
    return new TextPart(fields.text as string, { sourceRef: (fields.source_ref as string | null) ?? null });
  }

  toRecord(): Record<string, unknown> {
    return { text: this.text, source_ref: this.sourceRef };
  }
}

export interface ImagePartOptions {
  data?: Uint8Array | null;
  url?: string | null;
  mediaType?: string | null;
  sourceRef?: string | null;
  detail?: ImageDetail | null;
}

/** Image bytes or a remote reference; construction never dereferences URLs. */
export class ImagePart {
  static readonly qualifiedName: string = 'tensorcode.ops.text.messages.ImagePart';
  static readonly recordFields = ['data', 'url', 'media_type', 'source_ref', 'detail'] as const;
  readonly data: Uint8Array | null;
  readonly url: string | null;
  readonly mediaType: string | null;
  readonly sourceRef: string | null;
  readonly detail: ImageDetail | null;

  constructor(options: ImagePartOptions) {
    const data = options.data ?? null;
    const url = options.url ?? null;
    if ((data === null) === (url === null)) throw new ValueError('ImagePart requires exactly one of data or url');
    if (data !== null && !(data instanceof Uint8Array)) throw new TypeError('ImagePart.data must be bytes');
    if (url !== null) {
      if (typeof url !== 'string') throw new TypeError('ImagePart.url must be a string');
      const scheme = /^([A-Za-z][A-Za-z0-9+.-]*):/.exec(url)?.[1]?.toLowerCase();
      if (scheme !== 'http' && scheme !== 'https' && scheme !== 'data') throw new ValueError('ImagePart URL must use http, https or data');
    }
    const mediaType = options.mediaType ?? null;
    if (mediaType !== null && typeof mediaType !== 'string') throw new TypeError('ImagePart.media_type must be a string or None');
    const sourceRef = options.sourceRef ?? null;
    if (sourceRef !== null && typeof sourceRef !== 'string') throw new TypeError('ImagePart.source_ref must be a string or None');
    const detail = options.detail ?? null;
    if (detail !== null && detail !== 'low' && detail !== 'high' && detail !== 'auto') {
      throw new ValueError('ImagePart.detail must be low, high, auto or None');
    }
    this.data = data === null ? null : data.slice();
    this.url = url;
    this.mediaType = mediaType;
    this.sourceRef = sourceRef;
    this.detail = detail;
    Object.freeze(this);
  }

  static fromRecord(fields: Record<string, unknown>): ImagePart {
    return new ImagePart({
      data: (fields.data as Uint8Array | null) ?? null, url: (fields.url as string | null) ?? null,
      mediaType: (fields.media_type as string | null) ?? null, sourceRef: (fields.source_ref as string | null) ?? null,
      detail: (fields.detail as ImageDetail | null) ?? null,
    });
  }

  toRecord(): Record<string, unknown> {
    return { data: this.data, url: this.url, media_type: this.mediaType, source_ref: this.sourceRef, detail: this.detail };
  }
}

export type MessagePart = TextPart | ImagePart;
export type MessageContent = string | readonly MessagePart[];

export class Message {
  static readonly qualifiedName: string = 'tensorcode.ops.text.messages.Message';
  static readonly recordFields = ['role', 'content'] as const;
  readonly role: MessageRole;
  /** Plain text, or a frozen (tuple) array of parts. */
  readonly content: MessageContent;

  constructor(role: MessageRole, content: string | Iterable<MessagePart>) {
    if (!['system', 'user', 'assistant', 'tool'].includes(role)) throw new ValueError('Unsupported message role');
    this.role = role;
    if (typeof content === 'string') {
      this.content = content;
    } else {
      if (content === null || content === undefined || typeof (content as Iterable<MessagePart>)[Symbol.iterator] !== 'function') {
        throw new TypeError('Message content must be text or a sequence of parts');
      }
      const parts = Object.freeze([...content]);
      if (!parts.length || !parts.every((part) => part instanceof TextPart || part instanceof ImagePart)) {
        throw new TypeError('Multipart message content requires TextPart or ImagePart values');
      }
      this.content = parts;
    }
    Object.freeze(this);
  }

  static fromRecord(fields: Record<string, unknown>): Message {
    return new Message(fields.role as MessageRole, fields.content as MessageContent);
  }

  toRecord(): Record<string, unknown> {
    return { role: this.role, content: this.content };
  }
}
