/**
 * Provider-neutral model requests used by all message operations (Python
 * ``tensorcode/ops/text/model.py``). FOUNDATION-OWNED: the text and tools
 * builders code against these contracts but do not edit this file.
 *
 * Synchronous in-process models implement {@link Model}. Network providers are
 * asynchronous in JavaScript and implement {@link AsyncModel}; operations wrapping
 * them are invoked with ``await operation.acall(...)``.
 */
import { ValueError } from '../../errors.js';
import { isPlainObject } from '../../_internal/json.js';
import { Message } from './messages.js';

/** A model returned a value that does not satisfy an operation contract. */
export class InvalidModelOutput extends ValueError {}

export interface ModelRequestOptions {
  instructions?: string | null;
  responseSchema?: Readonly<Record<string, unknown>> | null;
  schemaName?: string | null;
}

export class ModelRequest {
  static readonly qualifiedName: string = 'tensorcode.ops.text.model.ModelRequest';
  static readonly recordFields = ['messages', 'instructions', 'response_schema', 'schema_name'] as const;
  readonly messages: readonly Message[];
  readonly instructions: string | null;
  readonly responseSchema: Readonly<Record<string, unknown>> | null;
  readonly schemaName: string | null;

  constructor(messages: Iterable<Message>, options: ModelRequestOptions = {}) {
    const items = Object.freeze([...messages]);
    if (!items.length || !items.every((message) => message instanceof Message)) {
      throw new TypeError('ModelRequest.messages must be a nonempty Message sequence');
    }
    const instructions = options.instructions ?? null;
    if (instructions !== null && typeof instructions !== 'string') throw new TypeError('ModelRequest.instructions must be a string or None');
    this.messages = items;
    this.instructions = instructions;
    this.responseSchema = options.responseSchema ?? null;
    this.schemaName = options.schemaName ?? null;
    Object.freeze(this);
  }

  static fromRecord(fields: Record<string, unknown>): ModelRequest {
    return new ModelRequest(fields.messages as Message[], {
      instructions: (fields.instructions as string | null) ?? null,
      responseSchema: (fields.response_schema as Record<string, unknown> | null) ?? null,
      schemaName: (fields.schema_name as string | null) ?? null,
    });
  }

  toRecord(): Record<string, unknown> {
    return { messages: this.messages, instructions: this.instructions, response_schema: this.responseSchema, schema_name: this.schemaName };
  }
}

export interface ModelOutputOptions {
  text?: string | null;
  structured?: Readonly<Record<string, unknown>> | null;
  providerMetadata?: Readonly<Record<string, unknown>> | null;
}

export class ModelOutput {
  static readonly qualifiedName: string = 'tensorcode.ops.text.model.ModelOutput';
  static readonly recordFields = ['text', 'structured', 'provider_metadata'] as const;
  readonly text: string | null;
  readonly structured: Readonly<Record<string, unknown>> | null;
  readonly providerMetadata: Readonly<Record<string, unknown>> | null;

  constructor(options: ModelOutputOptions) {
    const text = options.text ?? null;
    const structured = options.structured ?? null;
    if (text === null && structured === null) throw new ValueError('ModelOutput requires text or structured output');
    if (text !== null && typeof text !== 'string') throw new TypeError('ModelOutput.text must be a string or None');
    if (structured !== null && !isPlainObject(structured)) throw new TypeError('ModelOutput.structured must be a mapping or None');
    this.text = text;
    this.structured = structured;
    this.providerMetadata = options.providerMetadata ?? null;
    Object.freeze(this);
  }

  static fromRecord(fields: Record<string, unknown>): ModelOutput {
    return new ModelOutput({
      text: (fields.text as string | null) ?? null,
      structured: (fields.structured as Record<string, unknown> | null) ?? null,
      providerMetadata: (fields.provider_metadata as Record<string, unknown> | null) ?? null,
    });
  }

  toRecord(): Record<string, unknown> {
    return { text: this.text, structured: this.structured, provider_metadata: this.providerMetadata };
  }
}

/** Synchronous provider-neutral model: ``complete(ModelRequest) -> ModelOutput``. */
export interface Model {
  complete(request: ModelRequest): ModelOutput;
}

/** Asynchronous model: ``await acomplete(ModelRequest)``. */
export interface AsyncModel {
  acomplete(request: ModelRequest): Promise<ModelOutput>;
}

/** Optional fused transport: one output per request, in order. */
export interface BatchModel {
  completeBatch(requests: readonly ModelRequest[]): readonly ModelOutput[];
}

export interface AsyncBatchModel {
  acompleteBatch(requests: readonly ModelRequest[]): Promise<readonly ModelOutput[]>;
}

/** Answer several named requests about identical messages in one exchange. */
export interface QuestionModel {
  completeQuestions(requests: Readonly<Record<string, ModelRequest>>): Readonly<Record<string, ModelOutput>>;
}

export interface AsyncQuestionModel {
  acompleteQuestions(requests: Readonly<Record<string, ModelRequest>>): Promise<Readonly<Record<string, ModelOutput>>>;
}

function hasMethod(value: unknown, name: string): boolean {
  return typeof value === 'object' && value !== null && typeof (value as Record<string, unknown>)[name] === 'function';
}

export const isModel = (value: unknown): value is Model => hasMethod(value, 'complete');
export const isAsyncModel = (value: unknown): value is AsyncModel => hasMethod(value, 'acomplete');
export const isBatchModel = (value: unknown): value is BatchModel => hasMethod(value, 'completeBatch');
export const isAsyncBatchModel = (value: unknown): value is AsyncBatchModel => hasMethod(value, 'acompleteBatch');
export const isQuestionModel = (value: unknown): value is QuestionModel => hasMethod(value, 'completeQuestions');
export const isAsyncQuestionModel = (value: unknown): value is AsyncQuestionModel => hasMethod(value, 'acompleteQuestions');
