/**
 * Explicit action execution and observation-driven model-policy replanning
 * (Python ``tensorcode/_internal/execution/planning.py``).
 *
 * Text generated by a planner is inert. Applications explicitly construct
 * structured plans and provide both an action registry and a policy that
 * consumes observations.
 */
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { ValueError } from '../../errors.js';
import {
  isPlainObject, isPythonNumber, orderedEntries, orderedObject, parseJsonStrict, pythonJsonDumps, transferPythonNumberKind,
  type JsonObject, type JsonValue,
} from '../json.js';

/** Caller data (state, observations, arguments) is written as Python ``json.dumps`` writes it: no float schema. */
const NO_FLOAT_KEYS: ReadonlySet<string> = new Set();
import { atomicWriteFile } from '../files.js';
import { ActionOutcome } from '../../tools/actions.js';
import { deepClone } from './clone.js';
import { describePythonError, pythonErrorMessage, pythonErrorName } from '../pythonErrors.js';
import { actionSignature, bindArguments, type ActionSignature, type ResolvedSignature } from './signature.js';

export { withSignature, type ActionSignature, type ActionParameter } from './signature.js';

/**
 * Copy strictly JSON data without coercing tuples (frozen arrays), keys, or
 * custom objects (Python ``_json``).
 */
export function strictJson(value: unknown): JsonValue {
  if (value === null || typeof value === 'string' || typeof value === 'boolean') return value;
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (isPythonNumber(value) && Number.isFinite(value.value)) return value.value;
  // Copies keep Python number kinds (``1.0``) and dict insertion order.
  if (Array.isArray(value) && !Object.isFrozen(value)) {
    const result = value.map(strictJson);
    value.forEach((item, index) => transferPythonNumberKind(result, index, value, index, item));
    return result;
  }
  if (isPlainObject(value)) {
    const result = orderedObject(orderedEntries(value).map(([key, item]) => [key, strictJson(item)] as const));
    for (const key of Object.keys(value)) transferPythonNumberKind(result, key, value, key);
    return result;
  }
  throw new ValueError('trajectory values must use finite JSON types and string keys');
}

/** ``target[key] = source[key]`` for a record field, keeping a scalar's Python number kind. */
function keepKind(target: object, source: object, key: string, value: unknown): void {
  transferPythonNumberKind(target, key, source, key, value);
}

function nonemptyText(value: unknown): value is string {
  return typeof value === 'string' && Boolean(value.trim());
}

/** One step naming a registered action, its JSON arguments and an optional expectation. */
export class PlanStep {
  static readonly qualifiedName: string = 'tensorcode._internal.execution.planning.PlanStep';
  static readonly recordFields = ['action', 'arguments', 'expected_observation'] as const;
  readonly action: string;
  readonly arguments: Record<string, unknown>;
  readonly expectedObservation: unknown;

  constructor(action: string, args: Record<string, unknown> = {}, expectedObservation: unknown = null) {
    this.action = action;
    this.arguments = args;
    this.expectedObservation = expectedObservation;
    Object.freeze(this);
  }

  static fromRecord(fields: Record<string, unknown>): PlanStep {
    return new PlanStep(fields.action as string, (fields.arguments as Record<string, unknown> | undefined) ?? {}, fields.expected_observation ?? null);
  }

  toRecord(): Record<string, unknown> {
    return { action: this.action, arguments: this.arguments, expected_observation: this.expectedObservation };
  }
}

/** An explicit, validated sequence of {@link PlanStep}s for one plan candidate. */
export class ExecutablePlan {
  static readonly qualifiedName: string = 'tensorcode._internal.execution.planning.ExecutablePlan';
  static readonly recordFields = ['candidate_id', 'steps'] as const;
  readonly candidateId: string;
  readonly steps: readonly PlanStep[];

  constructor(candidateId: string, steps: readonly PlanStep[]) {
    this.candidateId = candidateId;
    this.steps = Array.isArray(steps) ? Object.freeze([...steps]) : steps;
    Object.freeze(this);
  }

  static fromRecord(fields: Record<string, unknown>): ExecutablePlan {
    return new ExecutablePlan(fields.candidate_id as string, fields.steps as PlanStep[]);
  }

  toRecord(): Record<string, unknown> {
    return { candidate_id: this.candidateId, steps: this.steps };
  }
}

export type ExperienceStatus = 'observed' | 'error';

/** Observed result (or error) of executing one plan step, with a unique source ID. */
export class OutcomeExperience {
  static readonly qualifiedName: string = 'tensorcode._internal.execution.planning.OutcomeExperience';
  static readonly recordFields = [
    'candidate_id', 'action', 'source_id', 'observation', 'status', 'arguments', 'expected_observation',
  ] as const;
  readonly candidateId: string;
  readonly action: string;
  readonly sourceId: string;
  readonly observation: unknown;
  readonly status: ExperienceStatus;
  readonly arguments: Record<string, unknown>;
  readonly expectedObservation: unknown;

  constructor(
    candidateId: string, action: string, sourceId: string, observation: unknown, status: ExperienceStatus,
    args: Record<string, unknown> = {}, expectedObservation: unknown = null,
  ) {
    this.candidateId = candidateId;
    this.action = action;
    this.sourceId = sourceId;
    this.observation = observation;
    this.status = status;
    this.arguments = args;
    this.expectedObservation = expectedObservation;
    Object.freeze(this);
  }

  static fromRecord(fields: Record<string, unknown>): OutcomeExperience {
    const result = new OutcomeExperience(fields.candidate_id as string, fields.action as string, fields.source_id as string,
      fields.observation, fields.status as ExperienceStatus, (fields.arguments as Record<string, unknown> | undefined) ?? {},
      fields.expected_observation ?? null);
    keepKind(result, fields, 'observation', result.observation);
    keepKind(result, fields, 'expected_observation', result.expectedObservation);
    return result;
  }

  toRecord(): Record<string, unknown> {
    const record = {
      candidate_id: this.candidateId, action: this.action, source_id: this.sourceId, observation: this.observation,
      status: this.status, arguments: this.arguments, expected_observation: this.expectedObservation,
    };
    keepKind(record, this, 'observation', this.observation);
    keepKind(record, this, 'expected_observation', this.expectedObservation);
    return record;
  }

  /** Attach an explicit retrospective label only to the observed candidate. */
  toTarget(outcome: number): { candidate_id: string; outcome: number } {
    if (typeof outcome !== 'number' || !Number.isFinite(outcome)) throw new ValueError('outcome must be a finite observed numeric label');
    return { candidate_id: this.candidateId, outcome };
  }

  private toEvidenceData(): Record<string, unknown> {
    const data = { action: this.action, status: this.status, observation: this.observation };
    keepKind(data, this, 'observation', this.observation);
    return data;
  }

  /** Render this observation as a ``{source_id, text}`` evidence item. */
  asEvidence(): { source_id: string; text: string } {
    return {
      source_id: this.sourceId,
      // Python ``json.dumps(..., sort_keys=True)``: observations have no float schema.
      text: pythonJsonDumps(this.toEvidenceData(), { sortKeys: true, allowNan: false, floatKeys: NO_FLOAT_KEYS }),
    };
  }
}

/** Input to the replan policy: state, previous plan, experiences so far and step index. */
export class ReplanRequest<S = unknown> {
  static readonly qualifiedName: string = 'tensorcode._internal.execution.planning.ReplanRequest';
  static readonly recordFields = ['state', 'previous_plan', 'experiences', 'step'] as const;
  readonly state: S;
  readonly previousPlan: ExecutablePlan;
  readonly experiences: readonly OutcomeExperience[];
  readonly step: number;

  constructor(state: S, previousPlan: ExecutablePlan, experiences: readonly OutcomeExperience[], step: number) {
    this.state = state;
    this.previousPlan = previousPlan;
    this.experiences = Object.freeze([...experiences]);
    this.step = step;
    Object.freeze(this);
  }

  static fromRecord(fields: Record<string, unknown>): ReplanRequest {
    return new ReplanRequest(fields.state, fields.previous_plan as ExecutablePlan, fields.experiences as OutcomeExperience[], fields.step as number);
  }

  toRecord(): Record<string, unknown> {
    return { state: this.state, previous_plan: this.previousPlan, experiences: this.experiences, step: this.step };
  }

  /** Experiences rendered as sourced evidence items. */
  get evidence(): { source_id: string; text: string }[] {
    return this.experiences.map((item) => item.asEvidence());
  }
}

export type PlanStopReason = 'completed' | 'abstained' | 'policy_error' | 'budget_exhausted';
const STOP_REASONS = new Set<string>(['completed', 'abstained', 'policy_error', 'budget_exhausted']);
const EXPERIENCE_FIELDS = ['candidate_id', 'action', 'source_id', 'observation', 'status', 'arguments', 'expected_observation'];
const TRAJECTORY_FIELDS = ['version', 'state', 'experiences', 'stop_reason', 'policy_errors'];

function sameKeys(value: Record<string, unknown>, expected: readonly string[]): boolean {
  const keys = Object.keys(value);
  return keys.length === expected.length && expected.every((key) => Object.prototype.hasOwnProperty.call(value, key));
}

/** Final state, experiences, ``stop_reason`` and any replan-policy errors. */
export class PlanExecutionResult<S = unknown> {
  static readonly qualifiedName: string = 'tensorcode._internal.execution.planning.PlanExecutionResult';
  static readonly recordFields = ['state', 'experiences', 'stop_reason', 'policy_errors'] as const;
  readonly state: S;
  readonly experiences: readonly OutcomeExperience[];
  readonly stopReason: PlanStopReason;
  readonly policyErrors: readonly string[];

  constructor(state: S, experiences: readonly OutcomeExperience[], stopReason: PlanStopReason, policyErrors: readonly string[] = []) {
    this.state = state;
    this.experiences = Array.isArray(experiences) ? Object.freeze([...experiences]) : experiences;
    this.stopReason = stopReason;
    this.policyErrors = Array.isArray(policyErrors) ? Object.freeze([...policyErrors]) : policyErrors;
    Object.freeze(this);
  }

  static fromRecord(fields: Record<string, unknown>): PlanExecutionResult {
    return new PlanExecutionResult(fields.state, fields.experiences as OutcomeExperience[], fields.stop_reason as PlanStopReason,
      (fields.policy_errors as string[] | undefined) ?? []);
  }

  toRecord(): Record<string, unknown> {
    return { state: this.state, experiences: this.experiences, stop_reason: this.stopReason, policy_errors: this.policyErrors };
  }

  /** The persisted JSON document (Python ``save`` payload). */
  toData(): JsonObject {
    if (!Array.isArray(this.experiences) || this.experiences.some((item) => !(item instanceof OutcomeExperience))) {
      throw new ValueError('experiences must be a tuple of OutcomeExperience records');
    }
    if (!Array.isArray(this.policyErrors)) throw new ValueError('policy_errors must be a tuple of strings');
    const data = {
      version: 1, state: this.state,
      experiences: this.experiences.map((item) => item.toRecord()),
      stop_reason: this.stopReason, policy_errors: [...this.policyErrors],
    };
    keepKind(data, this, 'state', this.state);
    PlanExecutionResult.fromData(data);
    return strictJson(data) as JsonObject;
  }

  /** Atomically persist validated JSON data, without executable code. */
  async save(path: string): Promise<void> {
    // Python ``json.dumps(data)``: caller state and observations have no float schema.
    const encoded = pythonJsonDumps(this.toData(), { allowNan: false, floatKeys: NO_FLOAT_KEYS });
    await atomicWriteFile(path, encoded);
  }

  /** Validate a persisted trajectory document (Python ``_from_data``). */
  static fromData(value: unknown): PlanExecutionResult<JsonValue> {
    const data = strictJson(value);
    if (!isPlainObject(data) || !sameKeys(data, TRAJECTORY_FIELDS)) throw new ValueError('invalid trajectory fields');
    if (typeof data.version !== 'number' || data.version !== 1) throw new ValueError('unsupported trajectory version');
    const reason = data.stop_reason;
    if (typeof reason !== 'string' || !STOP_REASONS.has(reason)) throw new ValueError('invalid trajectory stop_reason');
    const errors = data.policy_errors;
    if (!Array.isArray(errors) || errors.some((item) => !nonemptyText(item))) {
      throw new ValueError('policy_errors must be a list of nonempty strings');
    }
    if (Boolean(errors.length) !== (reason === 'policy_error')) throw new ValueError('policy errors must agree with stop_reason');
    const records = data.experiences;
    if (!Array.isArray(records)) throw new ValueError('experiences must be a list');
    const experiences: OutcomeExperience[] = [];
    const ids = new Set<string>();
    for (const item of records) {
      if (!isPlainObject(item) || !sameKeys(item, EXPERIENCE_FIELDS)) throw new ValueError('invalid action experience fields');
      if (['candidate_id', 'action', 'source_id'].some((key) => !nonemptyText(item[key]))) {
        throw new ValueError('action experience IDs and action must be nonempty strings');
      }
      const sourceId = item.source_id as string;
      if (ids.has(sourceId)) throw new ValueError('trajectory requires unique observation source IDs');
      ids.add(sourceId);
      if (item.status !== 'observed' && item.status !== 'error') throw new ValueError('invalid action experience status');
      if (!isPlainObject(item.arguments)) throw new ValueError('experience arguments must be a JSON object');
      if (item.status === 'error') {
        const error = item.observation;
        if (!isPlainObject(error) || !sameKeys(error, ['error_type', 'message'])
          || !nonemptyText(error.error_type) || typeof error.message !== 'string') {
          throw new ValueError('error observations require error_type and message');
        }
      }
      experiences.push(OutcomeExperience.fromRecord(item));
    }
    if (reason !== 'budget_exhausted' && !experiences.length) throw new ValueError('stop_reason requires an action observation');
    if (reason === 'completed' && experiences[experiences.length - 1]!.status !== 'observed') {
      throw new ValueError('completed trajectories require a final observed outcome');
    }
    const result = new PlanExecutionResult(data.state as JsonValue, experiences, reason as PlanStopReason, errors as string[]);
    keepKind(result, data, 'state', result.state);
    return result;
  }

  /** Load and validate a trajectory saved with {@link save}. */
  static async load(path: string): Promise<PlanExecutionResult<JsonValue>> {
    const text = await readFile(path, 'utf8');
    let data: JsonValue;
    try {
      data = parseJsonStrict(text);
    } catch (error) {
      if (error instanceof SyntaxError && /Duplicate/.test(error.message)) throw new ValueError('duplicate trajectory field', { cause: error });
      throw new ValueError(`invalid trajectory JSON: ${(error as Error).message}`, { cause: error });
    }
    return PlanExecutionResult.fromData(data);
  }
}

/**
 * A registry action: receives a copy of the state and a copy of the step's JSON
 * arguments (Python ``action(state, **arguments)``) and returns an
 * {@link ActionOutcome}, synchronously or asynchronously. The keyword
 * parameters it destructures from ``args`` are its signature.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type PlanAction<S = any> = (state: S, args: any) => ActionOutcome<S> | Promise<ActionOutcome<S>>;

/** A replan policy: returns the next explicit plan, or ``null`` to abstain. */
export type ReplanPolicy<S = any> = (request: ReplanRequest<S>) => unknown;

/**
 * Execute one validated step, observe, and ask the policy for a new plan.
 *
 * Registry actions accept ``(state, arguments)`` and return ActionOutcome.
 * Failures are observations; external effects cannot be rolled back. The policy
 * must explicitly select subsequent actions; there is no first-action fallback.
 * Input state is copied; only returned ActionOutcome state advances the run.
 *
 * Validation binds every step's arguments against the action's keyword
 * parameters like Python's ``inspect.signature(action).bind(None, **arguments)``:
 * the properties the action destructures from its second parameter, or an
 * explicit signature ({@link withSignature} or the ``signatures`` option).
 * Error observations record Python exception names (``Error`` →
 * ``RuntimeError``; see ``pythonErrorName``).
 */
export class PlanExecutor<S = any> {
  static readonly qualifiedName: string = 'tensorcode._internal.execution.planning.PlanExecutor';
  readonly actions: ReadonlyMap<string, PlanAction<S>>;
  readonly replan: ReplanPolicy<S>;
  readonly maxSteps: number;
  readonly #signatures: ReadonlyMap<string, ResolvedSignature>;

  constructor(options: {
    actions: Record<string, PlanAction<S>> | Map<string, PlanAction<S>>; replan: ReplanPolicy<S>; maxSteps: number;
    /** Explicit keyword signatures by action name (override what is read from each function). */
    signatures?: Readonly<Record<string, ActionSignature>> | null;
  }) {
    const { replan, maxSteps } = options;
    if (typeof replan !== 'function') throw new TypeError('replan must be an explicit callable policy');
    if (typeof maxSteps !== 'number' || !Number.isInteger(maxSteps) || maxSteps < 0) throw new ValueError('max_steps must be a nonnegative integer');
    const actions = new Map<string, PlanAction<S>>(options.actions instanceof Map ? options.actions : Object.entries(options.actions ?? {}));
    for (const [name, fn] of actions) {
      if (!nonemptyText(name) || typeof fn !== 'function') throw new ValueError('actions must map nonempty names to callables');
    }
    const explicit = options.signatures ?? {};
    if (explicit === null || typeof explicit !== 'object') throw new TypeError('signatures must map action names to signatures');
    for (const name of Object.keys(explicit)) {
      if (!actions.has(name)) throw new ValueError(`signature for unregistered action ${JSON.stringify(name)}`);
    }
    this.#signatures = new Map([...actions].map(([name, fn]) => [name, actionSignature(fn, explicit[name] ?? null)]));
    this.actions = actions;
    this.replan = replan;
    this.maxSteps = maxSteps;
    Object.freeze(this);
  }

  /** Validate an entire plan before any effect; returns an independent copy. */
  validate(plan: unknown): ExecutablePlan {
    if (!(plan instanceof ExecutablePlan)) throw new TypeError('policy must return an explicit ExecutablePlan; generated text is inert');
    if (!nonemptyText(plan.candidateId)) throw new ValueError('plan requires a candidate_id');
    if (!Array.isArray(plan.steps) || !plan.steps.length) throw new ValueError('plan requires explicit nonempty steps');
    for (const step of plan.steps) {
      if (!(step instanceof PlanStep) || !nonemptyText(step.action) || !this.actions.has(step.action)) {
        throw new ValueError('every step must name an explicitly registered action');
      }
      if (!isPlainObject(step.arguments)) throw new ValueError('step arguments must be a JSON object');
      strictJson(step.arguments);
      strictJson(step.expectedObservation);
      bindArguments(this.#signatures.get(step.action)!, step.arguments);
    }
    return new ExecutablePlan(plan.candidateId, plan.steps.map((step) => new PlanStep(
      step.action, strictJson(step.arguments) as Record<string, unknown>, strictJson(step.expectedObservation),
    )));
  }

  /** Validate the whole initial plan, then execute at most ``maxSteps`` actions. */
  async call(state: S, plan: ExecutablePlan): Promise<PlanExecutionResult<S>> {
    let current = this.validate(plan);
    let value = strictJson(state) as S;
    const experiences: OutcomeExperience[] = [];
    for (let index = 0; index < this.maxSteps; index += 1) {
      const step = current.steps[0]!;
      let observation: unknown;
      let status: ExperienceStatus;
      let done: boolean;
      try {
        const outcome = await this.actions.get(step.action)!(deepClone(value), deepClone(step.arguments) as Record<string, JsonValue>);
        if (!(outcome instanceof ActionOutcome) || typeof outcome.done !== 'boolean') {
          throw new TypeError('action must return ActionOutcome with boolean done');
        }
        const next = strictJson(outcome.state) as S;
        observation = strictJson(outcome.receipt);
        value = next;
        status = 'observed';
        done = outcome.done;
      } catch (error) {
        observation = { error_type: pythonErrorName(error), message: pythonErrorMessage(error) };
        status = 'error';
        done = false;
      }
      experiences.push(new OutcomeExperience(current.candidateId, step.action, `action:${randomUUID().replaceAll('-', '')}`,
        observation, status, deepClone(step.arguments), deepClone(step.expectedObservation)));
      if (done) return new PlanExecutionResult(value, experiences, 'completed');
      if (index + 1 === this.maxSteps) break;
      const request = new ReplanRequest(deepClone(value), deepClone(current), experiences.map((item) => deepClone(item)), index + 1);
      try {
        const proposed = await this.replan(request);
        if (proposed === null || proposed === undefined) return new PlanExecutionResult(value, experiences, 'abstained');
        current = this.validate(proposed);
      } catch (error) {
        return new PlanExecutionResult(value, experiences, 'policy_error', [describePythonError(error)]);
      }
    }
    return new PlanExecutionResult(value, experiences, 'budget_exhausted');
  }
}
