"""Generate src/_internal/tokenizers/blankTokenizers.generated.ts from the installed transformers.

Run with the Python package environment:

    ../python/.venv/bin/python scripts/codegen/blank_tokenizers.py

``AutoTokenizer.from_pretrained`` on a checkpoint without any tokenizer files
constructs the model type's tokenizer class with its defaults (a vocabulary of
special tokens only). The table records that tokenizer's backend
(``backend_tokenizer.to_str()``) per native ``model_type`` so the TypeScript
loader can reproduce it.
"""
from __future__ import annotations

import json
import tempfile
from pathlib import Path

from transformers import AutoConfig, AutoTokenizer

ROOT = Path(__file__).resolve().parents[2]
# Native model types whose AutoTokenizer class can be built without files.
TYPES = ['albert', 'bert', 'clip', 'clip_text_model', 'deberta-v2', 'distilbert', 'electra', 'roberta', 't5']


def main():
    table = {}
    for model_type in TYPES:
        with tempfile.TemporaryDirectory() as directory:
            AutoConfig.for_model(model_type).save_pretrained(directory)
            try:
                tokenizer = AutoTokenizer.from_pretrained(directory)
            except ValueError:  # the class cannot be built without files (Python raises too)
                continue
        table[model_type] = {'class': type(tokenizer).__name__, 'json': tokenizer.backend_tokenizer.to_str()}
    text = json.dumps(table, indent=2, sort_keys=True)
    out = ROOT / 'src' / '_internal' / 'tokenizers' / 'blankTokenizers.generated.ts'
    out.write_text(
        '// Generated by scripts/codegen/blank_tokenizers.py from transformers; do not edit.\n'
        '/**\n'
        ' * ``AutoTokenizer.from_pretrained`` for a checkpoint without tokenizer files:\n'
        ' * the model type\'s tokenizer class built with its defaults\n'
        ' * (``backend_tokenizer.to_str()``), keyed by ``model_type``.\n'
        ' */\n'
        f'export const BLANK_TOKENIZERS: Readonly<Record<string, {{ class: string; json: string }}>> = {text};\n')


if __name__ == '__main__':
    main()
