"""Generate src/_internal/native/diffusersDefaults.generated.ts from the installed diffusers.

    ../python/.venv/bin/python scripts/codegen/diffusers_defaults.py

``ImageDecoder`` persists each component's resolved configuration
(``{k: v for k, v in component.config.items() if not k.startswith('_')}``): the
constructor defaults overlaid with every supplied key (diffusers keeps unknown
keys in ``config``).
"""
from __future__ import annotations

import inspect
import json
from pathlib import Path

import diffusers
from diffusers import AutoencoderKL, DDIMScheduler, UNet2DConditionModel

ROOT = Path(__file__).resolve().parents[2]


def defaults(cls):
    result = {}
    for name, parameter in inspect.signature(cls.__init__).parameters.items():
        if name == 'self' or parameter.kind not in (parameter.POSITIONAL_OR_KEYWORD, parameter.KEYWORD_ONLY):
            continue
        result[name] = parameter.default
    return json.loads(json.dumps(result))


def main():
    tables = {cls.__name__: defaults(cls) for cls in (UNet2DConditionModel, AutoencoderKL, DDIMScheduler)}
    body = (
        '/* eslint-disable */\n'
        '// GENERATED by scripts/codegen/diffusers_defaults.py from diffusers '
        f'{diffusers.__version__}. Do not edit by hand.\n'
        "import { parseJsonStrict, type JsonObject } from '../json.js';\n\n"
        f'export const DIFFUSERS_VERSION = {json.dumps(diffusers.__version__)};\n\n'
        # JSON text parsed losslessly at import keeps Python float defaults (``1.0``).
        'export const DIFFUSERS_CONFIG_DEFAULTS: Record<string, JsonObject> = '
        f'parseJsonStrict({json.dumps(json.dumps(tables, indent=2))}) as Record<string, JsonObject>;\n'
    )
    target = ROOT / 'src' / '_internal' / 'native' / 'diffusersDefaults.generated.ts'
    target.write_text(body)
    print(f'wrote {target}')


if __name__ == '__main__':
    main()
