"""Generate src/_internal/native/defaults.generated.ts from the installed transformers.

Run with the Python package environment:

    ../python/.venv/bin/python scripts/codegen/native_defaults.py

The TypeScript native configuration emulation (``NativeConfig``) uses these
tables to reproduce ``PreTrainedConfig.to_dict()``/``to_json_string()``.
"""
from __future__ import annotations

import json
from pathlib import Path

import transformers
from transformers import AutoConfig, PretrainedConfig, GenerationConfig

ROOT = Path(__file__).resolve().parents[2]
TYPES = ['albert', 'bert', 'roberta', 'electra', 'distilbert', 't5', 'vit', 'clip', 'clip_text_model', 'clip_vision_model', 'deberta-v2',
         'llama', 'idefics3', 'idefics3_vision']


def clean(d):
    d = dict(d)
    d.pop('transformers_version', None)
    return d


def main():
    base = clean(PretrainedConfig().to_dict())
    classes, maps = {}, {}
    for model_type in TYPES:
        config = AutoConfig.for_model(model_type)
        classes[model_type] = clean(config.to_dict())
        maps[model_type] = dict(type(config).attribute_map)
    generation = clean(GenerationConfig().to_dict())
    def table(name, type_, value):
        # Embedded as JSON text parsed losslessly at import, so Python float
        # defaults (``initializer_factor: 1.0``) keep their float kind.
        text = json.dumps(value, indent=2, sort_keys=True)
        return f'export const {name}: {type_} = parseJsonStrict({json.dumps(text)}) as {type_};\n'

    body = (
        '/* eslint-disable */\n'
        '// GENERATED by scripts/codegen/native_defaults.py from transformers '
        f'{transformers.__version__}. Do not edit by hand.\n'
        "import { parseJsonStrict, type JsonObject } from '../json.js';\n\n"
        f"export const TRANSFORMERS_VERSION = {json.dumps(transformers.__version__)};\n\n"
        + table('BASE_CONFIG_DEFAULTS', 'JsonObject', base) + '\n'
        + table('CLASS_CONFIG_DEFAULTS', 'Record<string, JsonObject>', classes) + '\n'
        + f'export const ATTRIBUTE_MAPS: Record<string, Record<string, string>> = {json.dumps(maps, indent=2, sort_keys=True)};\n\n'
        + table('GENERATION_CONFIG_DEFAULTS', 'JsonObject', generation)
    )
    target = ROOT / 'src' / '_internal' / 'native' / 'defaults.generated.ts'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body)
    print(f'wrote {target}')


if __name__ == '__main__':
    main()
